### PR TITLE
Dockerizing application for local development

### PR DESCRIPTION
**Pull request by blong14**
**Why:** To have consistent local setup for developers.

**How:** Added docker file and updated database variables. Also add a dev.secrets.exs.example file

### CODE REVIEW

**Comment by achariam** [comment]
Hey @blong14 this looks great! thank you for taking the time to write it. I'm not super familiar with docker development. 

I understand the basic concept of containerization, would be curious about the overhead it adds, and whether it is necessary for a simple app such as this one? Just interested to learn more, going to try setting up this branch on my machine to test it out.

**Comment by blong14** [comment]
Hi @achariam thanks for giving this a look. I wanted to put a little more in the README as far as instruction goes for the development process but ran out of time before I had to leave for vacation. Additions that I can make are how to `exec` in the running container to migrate and seed the database (I'll add those steps soon). 

My thoughts were that if someone, like me, who doesn't know anything about Elixir or Phoenix could build and start the container without having to know how to install any of those dependencies on their local machine. The changes that have been up to this point would allow contributors to develop with or without the containers. I personally like dockerizing all apps no matter how big or small just so that environments between contributors are consistent. 

You'll also notice that there is a mailhog container that I have used in the past to catch emails. I wasn't sure how to set this up with Mailgun or even if that would be valuable as Mailgun may have a way to fake send emails locally?? 

If you run into issues with running the app in the container let me know and I can add more instructions in the README. I did test things a bit to make sure that I could make a change on my host in one of the controllers/models and would see that the app is recompiled. That seemed to work as expected. 

One last note: if the postgres container is destroyed and removed the data will be destroyed as well. Not sure if thats a big deal or not as you already have a way to seed the database. This is just something to keep in mind.

**Comment by blong14** [comment]
@achariam updated README.

**Comment by achariam** [comment]
Hey @blong14 sorry for the late reply on this. I think everything looks good, docker is pretty neat. 

Your rational for docker makes sense, and I think the Readme is improved as well, so thank you.

There is a way to test mailgun e-mails locally as noted [here on the hex repo](https://github.com/chrismccord/mailgun#test-mode). I can look into mailhog and see if it helps, but that's a good thing to note as well.

I don't think there should be any issue with destroying the postgres container locally. But thanks for the heads up, I didn't know that :)

Again, thanks for all the work on this. Let me know if I can help with anything as well.

**Pull request merged**
